# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
# and https://golangci-lint.run/

run:
  skip-files:
    - zz_generated*
  timeout: 3m
  go: 1.18

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    - path: cmd/
      linters:
        - errcheck

linters:
  disable: 
    - typecheck
  enable: # some linters are disabled with go1.18. See https://github.com/golangci/golangci-lint/issues/2649
    - nilerr
    - whitespace
    - gofmt
    - misspell

linters-settings:
  gosimple:
    checks: [ "-S1019" ]     
