name: Lint Full Codebase

on: [ push ]

jobs:
  golangci:
    name: Go Linter
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run golangci-lint
        env:
          CGO_ENABLED: 0
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.50.1
          args: -c=".github/linters/.golangci.yml"

  super-linter:
    name: Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Run super-linter
        uses: github/super-linter/slim@v4 # slim image has - 2gb and excludes support for languages we don't use
        env:
          VALIDATE_ALL_CODEBASE: false # only new or edited files. A broken change that has already been merged will not be picked up a second time!
          FILTER_REGEX_EXCLUDE: vendor/*
          # From docs: "If any one of the variables are set to true, we default to leaving any unset variable to false"
          VALIDATE_MARKDOWN: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_YAML: true
          VALIDATE_BASH: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          LINTER_RULES_PATH: .github/linters
